spring.application.name=service-booking-api
server.port=8080

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ServiceBookingDB;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=Pass@word1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

GOOGLE_API_KEY=AIzaSyBpQsalWqFrQ4jrXN4l_p3EY8YcEefHDZY
